#############################################################################
# Makefile for building: ia_dev
# Generated by qmake (2.01a) (Qt 4.8.7) on: mar. janv. 29 10:30:15 2019
# Project:  ia_dev.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ia_dev.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-agent \
		sub-ktbs \
		sub-simulation \
		sub-graphicsview \
		sub-radical_interactionnism \
		sub-view

agent//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) agent/ || $(MKDIR) agent/ 
	cd agent/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/agent/agent.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-agent-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) agent/ || $(MKDIR) agent/ 
	cd agent/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/agent/agent.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-agent: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE)
sub-agent-make_default-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) 
sub-agent-make_default: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) 
sub-agent-make_first-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) first
sub-agent-make_first: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) first
sub-agent-all-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) all
sub-agent-all: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) all
sub-agent-clean-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) clean
sub-agent-clean: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) clean
sub-agent-distclean-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) distclean
sub-agent-distclean: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) distclean
sub-agent-install_subtargets-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) install
sub-agent-install_subtargets: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) install
sub-agent-uninstall_subtargets-ordered: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-agent-uninstall_subtargets: agent//$(MAKEFILE) FORCE
	cd agent/ && $(MAKE) -f $(MAKEFILE) uninstall
ktbs//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ktbs/ || $(MKDIR) ktbs/ 
	cd ktbs/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/ktbs/ktbs.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-ktbs-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ktbs/ || $(MKDIR) ktbs/ 
	cd ktbs/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/ktbs/ktbs.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-ktbs: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE)
sub-ktbs-make_default-ordered: ktbs//$(MAKEFILE) sub-agent-make_default-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) 
sub-ktbs-make_default: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) 
sub-ktbs-make_first-ordered: ktbs//$(MAKEFILE) sub-agent-make_first-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) first
sub-ktbs-make_first: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) first
sub-ktbs-all-ordered: ktbs//$(MAKEFILE) sub-agent-all-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) all
sub-ktbs-all: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) all
sub-ktbs-clean-ordered: ktbs//$(MAKEFILE) sub-agent-clean-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) clean
sub-ktbs-clean: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) clean
sub-ktbs-distclean-ordered: ktbs//$(MAKEFILE) sub-agent-distclean-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ktbs-distclean: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) distclean
sub-ktbs-install_subtargets-ordered: ktbs//$(MAKEFILE) sub-agent-install_subtargets-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) install
sub-ktbs-install_subtargets: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) install
sub-ktbs-uninstall_subtargets-ordered: ktbs//$(MAKEFILE) sub-agent-uninstall_subtargets-ordered  FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-ktbs-uninstall_subtargets: ktbs//$(MAKEFILE) FORCE
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) uninstall
simulation//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) simulation/ || $(MKDIR) simulation/ 
	cd simulation/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/simulation/simulation.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-simulation-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) simulation/ || $(MKDIR) simulation/ 
	cd simulation/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/simulation/simulation.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-simulation: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE)
sub-simulation-make_default-ordered: simulation//$(MAKEFILE) sub-ktbs-make_default-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) 
sub-simulation-make_default: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) 
sub-simulation-make_first-ordered: simulation//$(MAKEFILE) sub-ktbs-make_first-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) first
sub-simulation-make_first: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) first
sub-simulation-all-ordered: simulation//$(MAKEFILE) sub-ktbs-all-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) all
sub-simulation-all: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) all
sub-simulation-clean-ordered: simulation//$(MAKEFILE) sub-ktbs-clean-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) clean
sub-simulation-clean: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) clean
sub-simulation-distclean-ordered: simulation//$(MAKEFILE) sub-ktbs-distclean-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) distclean
sub-simulation-distclean: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) distclean
sub-simulation-install_subtargets-ordered: simulation//$(MAKEFILE) sub-ktbs-install_subtargets-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) install
sub-simulation-install_subtargets: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) install
sub-simulation-uninstall_subtargets-ordered: simulation//$(MAKEFILE) sub-ktbs-uninstall_subtargets-ordered  FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-simulation-uninstall_subtargets: simulation//$(MAKEFILE) FORCE
	cd simulation/ && $(MAKE) -f $(MAKEFILE) uninstall
graphicsview//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) graphicsview/ || $(MKDIR) graphicsview/ 
	cd graphicsview/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/graphicsview/graphicsview.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-graphicsview-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) graphicsview/ || $(MKDIR) graphicsview/ 
	cd graphicsview/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/graphicsview/graphicsview.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-graphicsview: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE)
sub-graphicsview-make_default-ordered: graphicsview//$(MAKEFILE) sub-simulation-make_default-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) 
sub-graphicsview-make_default: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) 
sub-graphicsview-make_first-ordered: graphicsview//$(MAKEFILE) sub-simulation-make_first-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) first
sub-graphicsview-make_first: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) first
sub-graphicsview-all-ordered: graphicsview//$(MAKEFILE) sub-simulation-all-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) all
sub-graphicsview-all: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) all
sub-graphicsview-clean-ordered: graphicsview//$(MAKEFILE) sub-simulation-clean-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) clean
sub-graphicsview-clean: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) clean
sub-graphicsview-distclean-ordered: graphicsview//$(MAKEFILE) sub-simulation-distclean-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) distclean
sub-graphicsview-distclean: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) distclean
sub-graphicsview-install_subtargets-ordered: graphicsview//$(MAKEFILE) sub-simulation-install_subtargets-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) install
sub-graphicsview-install_subtargets: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) install
sub-graphicsview-uninstall_subtargets-ordered: graphicsview//$(MAKEFILE) sub-simulation-uninstall_subtargets-ordered  FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-graphicsview-uninstall_subtargets: graphicsview//$(MAKEFILE) FORCE
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) uninstall
radical_interactionnism//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) radical_interactionnism/ || $(MKDIR) radical_interactionnism/ 
	cd radical_interactionnism/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/radical_interactionnism/radical_interactionnism.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-radical_interactionnism-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) radical_interactionnism/ || $(MKDIR) radical_interactionnism/ 
	cd radical_interactionnism/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/radical_interactionnism/radical_interactionnism.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-radical_interactionnism: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE)
sub-radical_interactionnism-make_default-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-make_default-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) 
sub-radical_interactionnism-make_default: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) 
sub-radical_interactionnism-make_first-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-make_first-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) first
sub-radical_interactionnism-make_first: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) first
sub-radical_interactionnism-all-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-all-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) all
sub-radical_interactionnism-all: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) all
sub-radical_interactionnism-clean-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-clean-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) clean
sub-radical_interactionnism-clean: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) clean
sub-radical_interactionnism-distclean-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-distclean-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) distclean
sub-radical_interactionnism-distclean: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) distclean
sub-radical_interactionnism-install_subtargets-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-install_subtargets-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) install
sub-radical_interactionnism-install_subtargets: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) install
sub-radical_interactionnism-uninstall_subtargets-ordered: radical_interactionnism//$(MAKEFILE) sub-graphicsview-uninstall_subtargets-ordered  FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-radical_interactionnism-uninstall_subtargets: radical_interactionnism//$(MAKEFILE) FORCE
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) uninstall
view//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) view/ || $(MKDIR) view/ 
	cd view/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/view/view.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-view-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) view/ || $(MKDIR) view/ 
	cd view/ && $(QMAKE) /home/ptipc/Développement/IA_Dev/view/view.pro -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o $(MAKEFILE)
sub-view: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE)
sub-view-make_default-ordered: view//$(MAKEFILE) sub-radical_interactionnism-make_default-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) 
sub-view-make_default: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) 
sub-view-make_first-ordered: view//$(MAKEFILE) sub-radical_interactionnism-make_first-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) first
sub-view-make_first: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) first
sub-view-all-ordered: view//$(MAKEFILE) sub-radical_interactionnism-all-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) all
sub-view-all: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) all
sub-view-clean-ordered: view//$(MAKEFILE) sub-radical_interactionnism-clean-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) clean
sub-view-clean: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) clean
sub-view-distclean-ordered: view//$(MAKEFILE) sub-radical_interactionnism-distclean-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) distclean
sub-view-distclean: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) distclean
sub-view-install_subtargets-ordered: view//$(MAKEFILE) sub-radical_interactionnism-install_subtargets-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) install
sub-view-install_subtargets: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) install
sub-view-uninstall_subtargets-ordered: view//$(MAKEFILE) sub-radical_interactionnism-uninstall_subtargets-ordered  FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-view-uninstall_subtargets: view//$(MAKEFILE) FORCE
	cd view/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: ia_dev.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ia_dev.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 CONFIG+=debug -o Makefile ia_dev.pro

qmake_all: sub-agent-qmake_all sub-ktbs-qmake_all sub-simulation-qmake_all sub-graphicsview-qmake_all sub-radical_interactionnism-qmake_all sub-view-qmake_all FORCE

make_default: sub-agent-make_default-ordered sub-ktbs-make_default-ordered sub-simulation-make_default-ordered sub-graphicsview-make_default-ordered sub-radical_interactionnism-make_default-ordered sub-view-make_default-ordered FORCE
make_first: sub-agent-make_first-ordered sub-ktbs-make_first-ordered sub-simulation-make_first-ordered sub-graphicsview-make_first-ordered sub-radical_interactionnism-make_first-ordered sub-view-make_first-ordered FORCE
all: sub-agent-all-ordered sub-ktbs-all-ordered sub-simulation-all-ordered sub-graphicsview-all-ordered sub-radical_interactionnism-all-ordered sub-view-all-ordered FORCE
clean: sub-agent-clean-ordered sub-ktbs-clean-ordered sub-simulation-clean-ordered sub-graphicsview-clean-ordered sub-radical_interactionnism-clean-ordered sub-view-clean-ordered FORCE
distclean: sub-agent-distclean-ordered sub-ktbs-distclean-ordered sub-simulation-distclean-ordered sub-graphicsview-distclean-ordered sub-radical_interactionnism-distclean-ordered sub-view-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-agent-install_subtargets-ordered sub-ktbs-install_subtargets-ordered sub-simulation-install_subtargets-ordered sub-graphicsview-install_subtargets-ordered sub-radical_interactionnism-install_subtargets-ordered sub-view-install_subtargets-ordered FORCE
uninstall_subtargets: sub-agent-uninstall_subtargets-ordered sub-ktbs-uninstall_subtargets-ordered sub-simulation-uninstall_subtargets-ordered sub-graphicsview-uninstall_subtargets-ordered sub-radical_interactionnism-uninstall_subtargets-ordered sub-view-uninstall_subtargets-ordered FORCE

sub-agent-check_ordered: agent/$(MAKEFILE)
	cd agent/ && $(MAKE) -f $(MAKEFILE) check
sub-ktbs-check_ordered: ktbs/$(MAKEFILE) sub-agent-check_ordered 
	cd ktbs/ && $(MAKE) -f $(MAKEFILE) check
sub-simulation-check_ordered: simulation/$(MAKEFILE) sub-ktbs-check_ordered 
	cd simulation/ && $(MAKE) -f $(MAKEFILE) check
sub-graphicsview-check_ordered: graphicsview/$(MAKEFILE) sub-simulation-check_ordered 
	cd graphicsview/ && $(MAKE) -f $(MAKEFILE) check
sub-radical_interactionnism-check_ordered: radical_interactionnism/$(MAKEFILE) sub-graphicsview-check_ordered 
	cd radical_interactionnism/ && $(MAKE) -f $(MAKEFILE) check
sub-view-check_ordered: view/$(MAKEFILE) sub-radical_interactionnism-check_ordered 
	cd view/ && $(MAKE) -f $(MAKEFILE) check
check: sub-agent-check_ordered sub-ktbs-check_ordered sub-simulation-check_ordered sub-graphicsview-check_ordered sub-radical_interactionnism-check_ordered sub-view-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

